const PrivateKeyFormat = {
  JWK: "JWK",
  PEM: "PEM",
};

const ACCESS_TOKEN_ENV_VAR = "FCM_ACCESS_TOKEN";
const ADMIN_COOKIE_ENV_VAR = "FCM_COOKIE";

const THEME_HTML_FIELDS = [
  { name: "accountFooter", encoded: false },
  { name: "journeyFooter", encoded: false },
  { name: "journeyHeader", encoded: false },
  { name: "journeyJustifiedContent", encoded: false },
  { name: "journeyFooterScriptTag", encoded: true },
  { name: "accountFooterScriptTag", encoded: true },
];

const CSP_SUBDIR = "csp";
const CSP_POLICIES = ["enforced", "report-only"];

const ORG_PRIVILEGES_CONFIG = [
  "alphaOrgPrivileges",
  "bravoOrgPrivileges",
  "privilegeAssignments",
];

const STDOUT_OPTION = "stdout";
const STDOUT_OPTION_SHORT = "o";

const STDIN_OPTION = "stdin";
const STDIN_OPTION_SHORT = "i";

const COMMAND = {
  ALL: "all",
  ALL_STATIC: "all-static",
  AUTH_TREE: "journeys",
  CONNECTOR_DEFINITIONS: "connector-definitions",
  CONNECTOR_MAPPINGS: "connector-mappings",
  COOKIE_DOMAINS: "cookie-domains",
  CORS: "cors",
  CSP: "csp",
  CUSTOM_NODES: "custom-nodes",
  MANAGED_OBJECTS: "managed-objects",
  EMAIL_TEMPLATES: "email-templates",
  EMAIL_PROVIDER: "email-provider",
  THEMES: "themes",
  REMOTE_SERVERS: "remote-servers",
  SCRIPTS: "scripts",
  SERVICES: "services",
  AUTHENTICATION: "authentication",
  TERMS_AND_CONDITIONS: "terms-and-conditions",
  PASSWORD_POLICY: "password-policy",
  UI_CONFIG: "ui-config",
  IDM_ENDPOINTS: "endpoints",
  IDM_SCHEDULES: "schedules",
  IDM_ACCESS_CONFIG: "access-config",
  IGA_WORKFLOWS: "iga-workflows",
  KBA: "kba",
  INTERNAL_ROLES: "internal-roles",
  SECRETS: "secrets",
  ESVS: "variables",
  SECRET_MAPPINGS: "secret-mappings",
  OAUTH2_AGENTS: "oauth2-agents",
  AUTHZ_POLICIES: "authz-policies",
  SERVICE_OBJECTS: "service-objects",
  LOCALES: "locales",
  AUDIT: "audit",
  CONFIG_METADATA: "config-metadata",
  VERSION: "version",
  TEST: "test",
  ORG_PRIVILEGES: "org-privileges",
  RAW: "raw",
  RESTART_TENANT: "restart",
  SAML: "saml",
  TELEMETRY: "telemetry",
  IDM_AUTHENTICATION: "idm-authentication",
  JOURNEYS: "journeys",
  TENANT_CONFIG: "tenant-config",
};

const DEPLOYMENT_COMMANDS = {
  PLATFORM: [
    COMMAND.AUTH_TREE,
    COMMAND.CONNECTOR_DEFINITIONS,
    COMMAND.CONNECTOR_MAPPINGS,
    COMMAND.COOKIE_DOMAINS,
    COMMAND.CORS,
    COMMAND.MANAGED_OBJECTS,
    COMMAND.EMAIL_TEMPLATES,
    COMMAND.EMAIL_PROVIDER,
    COMMAND.THEMES,
    COMMAND.REMOTE_SERVERS,
    COMMAND.SCRIPTS,
    COMMAND.SERVICES,
    COMMAND.AUTHENTICATION,
    COMMAND.TERMS_AND_CONDITIONS,
    COMMAND.PASSWORD_POLICY,
    COMMAND.UI_CONFIG,
    COMMAND.IDM_ENDPOINTS,
    COMMAND.IDM_SCHEDULES,
    COMMAND.IDM_ACCESS_CONFIG,
    COMMAND.KBA,
    COMMAND.INTERNAL_ROLES,
    COMMAND.SECRET_MAPPINGS,
    COMMAND.OAUTH2_AGENTS,
    COMMAND.AUTHZ_POLICIES,
    COMMAND.SERVICE_OBJECTS,
    COMMAND.LOCALES,
    COMMAND.AUDIT,
    COMMAND.ORG_PRIVILEGES,
    COMMAND.SAML,
    COMMAND.TEST,
  ],
  AM: [
    COMMAND.AUTH_TREE,
    COMMAND.COOKIE_DOMAINS,
    COMMAND.SCRIPTS,
    COMMAND.SERVICES,
    COMMAND.AUTHENTICATION,
    COMMAND.OAUTH2_AGENTS,
    COMMAND.AUTHZ_POLICIES,
    COMMAND.SAML,
    COMMAND.TEST,
  ],
};

const COMMAND_MAP = {
  all: [
    COMMAND.AUTH_TREE,
    COMMAND.CONNECTOR_DEFINITIONS,
    COMMAND.CONNECTOR_MAPPINGS,
    COMMAND.COOKIE_DOMAINS,
    COMMAND.CORS,
    COMMAND.MANAGED_OBJECTS,
    COMMAND.EMAIL_TEMPLATES,
    COMMAND.EMAIL_PROVIDER,
    COMMAND.THEMES,
    COMMAND.REMOTE_SERVERS,
    COMMAND.SCRIPTS,
    COMMAND.SERVICES,
    COMMAND.AUTHENTICATION,
    COMMAND.TERMS_AND_CONDITIONS,
    COMMAND.PASSWORD_POLICY,
    COMMAND.UI_CONFIG,
    COMMAND.IDM_ENDPOINTS,
    COMMAND.IDM_SCHEDULES,
    COMMAND.IDM_ACCESS_CONFIG,
    COMMAND.KBA,
    COMMAND.INTERNAL_ROLES,
    COMMAND.SECRETS,
    COMMAND.ESVS,
    COMMAND.SECRET_MAPPINGS,
    COMMAND.OAUTH2_AGENTS,
    COMMAND.AUTHZ_POLICIES,
    COMMAND.SERVICE_OBJECTS,
    COMMAND.LOCALES,
    COMMAND.AUDIT,
    COMMAND.ORG_PRIVILEGES,
    COMMAND.SAML,
  ],
  "all-static": [
    COMMAND.CUSTOM_NODES,
    COMMAND.AUTH_TREE,
    COMMAND.CONNECTOR_DEFINITIONS,
    COMMAND.CONNECTOR_MAPPINGS,
    COMMAND.CORS,
    COMMAND.MANAGED_OBJECTS,
    COMMAND.EMAIL_TEMPLATES,
    COMMAND.EMAIL_PROVIDER,
    COMMAND.THEMES,
    COMMAND.REMOTE_SERVERS,
    COMMAND.SCRIPTS,
    COMMAND.SERVICES,
    COMMAND.SECRET_MAPPINGS,
    COMMAND.AUTHENTICATION,
    COMMAND.TERMS_AND_CONDITIONS,
    COMMAND.PASSWORD_POLICY,
    COMMAND.UI_CONFIG,
    COMMAND.IDM_ENDPOINTS,
    COMMAND.IDM_SCHEDULES,
    COMMAND.IDM_ACCESS_CONFIG,
    COMMAND.KBA,
    COMMAND.LOCALES,
    COMMAND.AUDIT,
    COMMAND.ORG_PRIVILEGES,
    COMMAND.IDM_AUTHENTICATION,
  ],
};

module.exports.PrivateKeyFormat = PrivateKeyFormat;
module.exports.THEME_HTML_FIELDS = THEME_HTML_FIELDS;
module.exports.CSP_POLICIES = CSP_POLICIES;
module.exports.CSP_SUBDIR = CSP_SUBDIR;
module.exports.ACCESS_TOKEN_ENV_VAR = ACCESS_TOKEN_ENV_VAR;
module.exports.ORG_PRIVILEGES_CONFIG = ORG_PRIVILEGES_CONFIG;
module.exports.STDOUT_OPTION = STDOUT_OPTION;
module.exports.STDOUT_OPTION_SHORT = STDOUT_OPTION_SHORT;
module.exports.STDIN_OPTION = STDIN_OPTION;
module.exports.STDIN_OPTION_SHORT = STDIN_OPTION_SHORT;
module.exports.ADMIN_COOKIE_ENV_VAR = ADMIN_COOKIE_ENV_VAR;
module.exports.DEPLOYMENT_COMMANDS = DEPLOYMENT_COMMANDS;
module.exports.COMMAND = COMMAND;
module.exports.COMMAND_MAP = COMMAND_MAP;
